apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: autoapply
spec:
  template:
    metadata:
      labels:
        app: autoapply
    spec:
      containers:
        - name: autoapply
          image: autoapply/autoapply:kubectl
          args: ["env:AUTOAPPLY_CONFIG"]
          env:
            - name: AUTOAPPLY_CONFIG
              value: |
                loop:
                  sleep: 60
                  commands:
                    - git clone --depth 1 https://github.com/autoapply/template-kubectl workspace/
                    - kubectl apply -f workspace/dev/
                server:
                  enabled: true
          ports:
            - containerPort: 3000
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
